language: node_js
node_js:
  - "0.10"

before_script:
  - npm run update-webdriver

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  - node_modules/.bin/protractor protractor.conf.js
