language: node_js
node_js:
  - "0.10"

before_script:
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 3

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  - node_modules/.bin/protractor protractor.conf.js
