'use strict';

angular.module('bby-query-mixer.stores').constant('regionsConfig', [ 
	{ text:"Choose a Region/State", value:false },
	{ text:"AL - Alabama", value:"AL" },
	{ text:"AK - Alaska", value:"AK" },
	{ text:"AP - Armed Forces Pacific", value:"AP" },
	{ text:"AE - Armed Forces Europe", value:"AE" },
	{ text:"AA - Armed Forces America", value:"AA" },
	{ text:"AZ - Arizona", value:"AZ" },
	{ text:"AR - Arkansas", value:"AR" },
	{ text:"CA - California", value:"" },
	{ text:"CO - Colorado", value:"" },
	{ text:"CT - Connecticut", value:"" },
	{ text:"DC - Washington D.C.", value:"" },
	{ text:"DE - Delaware", value:"" },
	{ text:"FL - Florida", value:"" },
	{ text:"GA - Georgia", value:"" },
	{ text:"GU - Guam", value:"" },
	{ text:"HI - Hawaii", value:"" },
	{ text:"ID - Idaho", value:"" },
	{ text:"IL - Illinois", value:"" },
	{ text:"IN - Indiana", value:"" },
	{ text:"IA - Iowa", value:"" },
	{ text:"KS - Kansas", value:"" },
	{ text:"KY - Kentucky", value:"" },
	{ text:"LA - Louisiana", value:"" },
	{ text:"ME - Maine", value:"" },
	{ text:"MD - Maryland", value:"" },
	{ text:"MA - Massachusetts", value:"" },
	{ text:"MI - Michigan", value:"" },
	{ text:"MN - Minnesota", value:"" },
	{ text:"MS - Mississippi", value:"" },
	{ text:"MO - Missouri", value:"" },
	{ text:"MT - Montana", value:"" },
	{ text:"NE - Nebraska", value:"" },
	{ text:"NV - Nevada", value:"" },
	{ text:"NH - New Hampshire", value:"" },
	{ text:"NJ - New Jersey", value:"" },
	{ text:"NM - New Mexico", value:"" },
	{ text:"NY - New York", value:"" },
	{ text:"NC - North Carolina", value:"" },
	{ text:"ND - North Dakota", value:"" },
	{ text:"OH - Ohio", value:"" },
	{ text:"OK - Oklahoma", value:"" },
	{ text:"OR - Oregon", value:"" },
	{ text:"PA - Pennsylvania", value:"" },
	{ text:"PR - Puerto Rico", value:"" },
	{ text:"RI - Rhode Island", value:"" },
	{ text:"SC - South Carolina", value:"" },
	{ text:"SD - South Dakota", value:"" },
	{ text:"TN - Tennessee", value:"" },
	{ text:"TX - Texas", value:"" },
	{ text:"UT - Utah", value:"" },
	{ text:"VT - Vermont", value:"" },
	{ text:"VA - Virginia", value:"" },
	{ text:"VI - Virgin Island", value:"" },
	{ text:"WA - Washington", value:"" },
	{ text:"WV - West Virginia", value:"" },
	{ text:"WI - Wisconsin", value:"" },
	{ text:"WY - Wyoming", value:"" },
]);